### ISSUE TITLE
Can't open wallet in Linux

### ISSUE THREAD

**Issue by RagnarLodbrok79** [decenomy/KYAN#20]
### Describe the issue
Getting an error when running ./kyan-qt

#### If so, please list the steps to reproduce below:
1. ./kyan-qt

### Expected behaviour
Should open wallet

### Actual behaviour
Shows an error

### Screenshots.
![Screenshot 2021-04-22 20 21 23](https://user-images.githubusercontent.com/79371412/115767978-ffb84900-a3a9-11eb-9d57-99483a8bf031.png)

### What version of Kyan Core are you using?
KYAN-0.15-Linux.zip from https://kyancoin.net/

### Machine specs:
- OS: LINUX enabled Chromebox
- CPU: intel i5
- RAM: 8 GB
- Disk size: 120 GB
- Disk Type (HD/SDD): External (USB 3 SSD)

**Comment by bedri** [comment]
@RagnarLodbrok79  Kyanite wallet is already running on your system. Check the running processes and stop the running Kyanite wallet and then rerun the QT wallet.
You can also reboot the computer and try to run the wallet again.
